# .github/workflows/monitor-pipc.yml
name: Monitor PIPC Website

on:
  schedule:
    # 매 6시간마다 실행 (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install axios cheerio
        
    - name: Run monitoring script
      run: node monitor.js
      env:
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        
    - name: Update last check file
      run: |
        echo "$(date)" > last_check.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add last_check.txt
        git diff --staged --quiet || git commit -m "Update last check time"
        git push
